### ISSUE TITLE
全局阻断报错

### ISSUE THREAD

**Issue by balaboooot** [KarisAya/nonebot_plugin_matcher_block#4]
```
08-28 19:18:09 [SUCCESS] nonebot | OneBot V11 2018909598 | [message.group.normal]: Message 2112884354 from XXXXX@[群:XXXXX] '添加阻断 签到 屏蔽 全局'
08-28 19:18:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.冷却)
08-28 19:18:09 [INFO] nonebot | Matcher(type='message', module=src.plugins.冷却) running complete
08-28 19:18:09 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.冷却) failed.
Traceback (most recent call last):
  File "D:\bot\nonebot\nb2\bot.py", line 16, in <module>
    nonebot.run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run    server.run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once    handle._run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\nonebot\nb2\src\plugins\冷却\__init__.py", line 152, in _
    group_config = {k:list(set(v.append(command))) for k,v in group_config.items()}
  File "D:\bot\nonebot\nb2\src\plugins\冷却\__init__.py", line 152, in <dictcomp>
    group_config = {k:list(set(v.append(command))) for k,v in group_config.items()}
TypeError: 'NoneType' object is not iterable
```

**Comment by balashen** [comment]
`08-28 19:18:09 [SUCCESS] nonebot | OneBot V11 2018909598 | [message.group.normal]: Message 2112884354 from 542588457@[群:165626882] '添加阻断 实况 屏蔽 全局'
08-28 19:18:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.冷却)
08-28 19:18:09 [INFO] nonebot | Matcher(type='message', module=src.plugins.冷却) running complete
08-28 19:18:09 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.冷却) failed.
Traceback (most recent call last):
  File "D:\bot\nonebot\nb2\bot.py", line 16, in <module>
    nonebot.run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run    server.run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once    handle._run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\nonebot\nb2\src\plugins\冷却\__init__.py", line 152, in _
    group_config = {k:list(set(v.append(command))) for k,v in group_config.items()}
  File "D:\bot\nonebot\nb2\src\plugins\冷却\__init__.py", line 152, in <dictcomp>
    group_config = {k:list(set(v.append(command))) for k,v in group_config.items()}
TypeError: 'NoneType' object is not iterable`
