### ISSUE TITLE
red适配器内使用时，查看阻断指令会报错

### ISSUE THREAD

**Issue by balaboooot** [KarisAya/nonebot_plugin_matcher_block#5]
```
10-22 22:44:32 [SUCCESS] nonebot | RedProtocol _qqid隐藏_ | [message.group]: Message from 阿巴阿巴 in 调试2: 查看阻断
10-22 22:44:32 [INFO] nonebot | Event will be handled by Matcher(type='message', module=src.plugins.冷却, lineno=234)
10-22 22:44:32 [INFO] nonebot | Matcher(type='message', module=src.plugins.冷却, lineno=234) running complete
10-22 22:44:32 [ERROR] nonebot | Running Matcher(type='message', module=src.plugins.冷却, lineno=234) failed.
Traceback (most recent call last):
  File "D:\bot\nonebot\nb2\bot.py", line 14, in <module>
    nonebot.run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 201, in run
    uvicorn.run(
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 821, in simple_run
    await handler(
  File "C:\Users\weatherbot\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\bot\nonebot\nb2\src\plugins\冷却\__init__.py", line 238, in _
    group_id = str(event.group_id)
AttributeError: 'GroupMessageEvent' object has no attribute 'group_id'
```

**Comment by KarisAya** [comment]
并不支持red
